### ISSUE TITLE
Add facebook 

### ISSUE THREAD

**Issue by ksiadz** [hs3city/inf_event_cli#18]
When event is created it should also post event at facebook.

**Comment by not7cd** [comment]
https://developers.facebook.com/docs/graph-api/reference/v2.3/event#Creating
Can't create event using their Graph API

**Comment by not7cd** [comment]
https://developers.facebook.com/docs/graph-api/reference/v2.3/event#Creating
http://facebook-sdk.readthedocs.io/en/latest/api.html
Can't create event using their Graph API
